baseURL = "https://danhughes.io"
languageCode = "en-gb"
title = "Dan Hughes"
publishdir = "dist"
copyright = "© 2019 Dan Hughes. [Some rights reserved](http://creativecommons.org/licenses/by/3.0/)."
assetdir = "."

[params]
author = "Dan Hughes"
authorimage = "headshot.png"
dateformat = "Jan 2, 2006"
stylesheets = [
	"css/main.css",
	"css/tokens.css",
	"node_modules/normalize.css/normalize.css",
	"node_modules/font-awesome/css/font-awesome.css"
]

[params.font]
name = "Libre Franklin"
weights = "300,400"

[[menu.main]]
name = "notes"
identifier = "notes"
url = "/notes"

[[params.social]]
name = "github"
url = "https://github.com/dan1elhughes"

[[params.social]]
name = "instagram"
url = "https://instagram.com/dan1elhughes"

[[params.social]]
name = "linkedin"
url = "https://linkedin.com/in/dan1elhughes"

[[params.social]]
name = "twitter"
url = "https://twitter.com/dan1elhughes"
