baseURL = "https://danhughes.io"
languageCode = "en-gb"
title = "Dan Hughes"
publishdir = "dist"
copyright = "© 2019 Dan Hughes. [Some rights reserved](http://creativecommons.org/licenses/by/3.0/)."

[params]
author = "Dan Hughes"
authorimage = "headshot.png"
dateformat = "Jan 2, 2006"

[params.font]
name = "Libre Franklin"
weights = "300,400"

[[menu.main]]
name = "notes"
identifier = "notes"
url = "/notes"

[params.social]
github = "dan1elhughes"
instagram = "dan1elhughes"
linkedin = "dan1elhughes"
twitter = "dan1elhughes"
