baseURL = "https://danhughes.io"
languageCode = "en-gb"
title = "Dan Hughes"
publishdir = "dist"
copyright = "© 2019 Dan Hughes. [Some rights reserved](http://creativecommons.org/licenses/by/3.0/)."
assetdir = "."

[params]
author = "Dan Hughes"
authorimage = "/img/headshot.png"
dateformat = "Jan 2, 2006"
description = "I'm a web engineer at Monzo. This is a public notebook."

[permalinks]
notes = "/:year/:month/:title/"

[params.unpkg]
css = [
	"normalize.css/normalize.css",
	"highlightjs/styles/solarized-dark.css"
]
js = [
	"highlightjs/highlight.pack.js"
]

[params.font]
name = "Libre Franklin"
weights = "300,400"

[[menu.main]]
name = "notes"
identifier = "notes"
url = "/notes"

[[params.social]]
name = "github"
url = "https://github.com/dan1elhughes"

[[params.social]]
name = "instagram"
url = "https://instagram.com/dh.gif"

[[params.social]]
name = "linkedin"
url = "https://linkedin.com/in/dan1elhughes"

[[params.social]]
name = "twitter"
url = "https://twitter.com/dan1elhughes"
