version: 2
jobs:
  prepare:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: "npm install"
      - run: "npm run prepare"
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
  compile:
    docker:
      - image: cibuilds/hugo:latest
    steps:
      - attach_workspace:
          at: ~/project
      - run: "hugo --minify"
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
  deploy:
    docker:
      - image: circleci/node:latest
    steps:
      - attach_workspace:
          at: ~/project
      - run: "npm run deploy"

workflows:
  version: 2
  build:
    jobs:
      - prepare
      - compile:
          requires:
            - prepare
      - deploy:
          requires:
            - compile
